import json
from pathlib import Path

from publishing.publish_result import (
    PublishResult
)


class DocusaurusPublisher:

    def publish(
        self,
        request
    ):
        """
        Generate a complete Docusaurus
        documentation project.
        """

        if not request.output_folder:

            return PublishResult(

                success=False,

                message=(
                    "Please provide an output "
                    "folder for the Docusaurus project."
                )

            ).to_dict()

        project_path = (
            Path(request.output_folder)
            / "docusaurus_project"
        )

        docs_path = (
            project_path
            / "docs"
        )

        pages_path = (
            project_path
            / "src"
            / "pages"
        )

        docs_path.mkdir(
            parents=True,
            exist_ok=True
        )

        pages_path.mkdir(
            parents=True,
            exist_ok=True
        )

        #
        # package.json
        #

        package_json = {

            "name": "docintel-documentation",

            "version": "1.0.0",

            "private": True,

            "scripts": {

                "start": "docusaurus start",

                "build": "docusaurus build",

                "serve": "docusaurus serve"

            },

            "dependencies": {

                "@docusaurus/core": "3.10.2",

                "@docusaurus/preset-classic": "3.10.2",

                "react": "^19.0.0",

                "react-dom": "^19.0.0"

            }

        }

        (
            project_path / "package.json"
        ).write_text(

            json.dumps(
                package_json,
                indent=2
            ),

            encoding="utf-8"

        )

        #
        # docusaurus.config.js
        #

        config_lines = [

            "const config = {",

            f"    title: {json.dumps(request.title)},",

            "    tagline: "
            "'Documentation generated by DocIntel AI',",

            "    url: 'http://localhost:3000',",

            "    baseUrl: '/',",

            "    onBrokenLinks: 'warn',",

            "    onBrokenMarkdownLinks: 'warn',",

            "    i18n: {",

            "        defaultLocale: 'en',",

            "        locales: ['en']",

            "    },",

            "    presets: [",

            "        [",

            "            'classic',",

            "            {",

            "                docs: {",

            "                    sidebarPath: "
            "require.resolve('./sidebars.js')",

            "                }",

            "            }",

            "        ]",

            "    ]",

            "};",

            "module.exports = config;"

        ]

        config = "\n".join(
            config_lines
        )

        (
            project_path
            / "docusaurus.config.js"
        ).write_text(

            config,

            encoding="utf-8"

        )

        #
        # sidebars.js
        #

        sidebar_lines = [

            "const sidebars = {",

            "    tutorialSidebar: [",

            "        'intro'",

            "    ]",

            "};",

            "module.exports = sidebars;"

        ]

        sidebars = "\n".join(
            sidebar_lines
        )

        (
            project_path / "sidebars.js"
        ).write_text(

            sidebars,

            encoding="utf-8"

        )

        #
        # Documentation
        #

        intro_lines = [

            "---",

            "sidebar_position: 1",

            "---",

            "",

            f"# {request.title}",

            "",

            request.content

        ]

        intro = "\n".join(
            intro_lines
        )

        (
            docs_path / "intro.md"
        ).write_text(

            intro,

            encoding="utf-8"

        )

        #
        # Homepage
        #

        homepage_lines = [

            "import React from 'react';",

            "import Layout from '@theme/Layout';",

            "import Link from '@docusaurus/Link';",

            "",

            "export default function Home() {",

            "    return (",

            "        <Layout",

            "            title='Documentation'",

            "            description='Documentation generated by DocIntel AI'",

            "        >",

            "            <main",

            "                style={{",

            "                    maxWidth: '900px',",

            "                    margin: '0 auto',",

            "                    padding: '80px 24px',",

            "                    textAlign: 'center'",

            "                }}",

            "            >",

            f"                <h1>{request.title}</h1>",

            "",

            "                <p>",

            "                    Documentation generated by DocIntel AI.",

            "                </p>",

            "",

            "                <Link",

            "                    className='button button--primary button--lg'",

            "                    to='/docs/intro'",

            "                >",

            "                    View Documentation",

            "                </Link>",

            "            </main>",

            "        </Layout>",

            "    );",

            "}"

        ]

        homepage = "\n".join(
            homepage_lines
        )

        (
            pages_path / "index.js"
        ).write_text(

            homepage,

            encoding="utf-8"

        )

        #
        # README
        #

        readme_lines = [

            f"# {request.title}",

            "",

            "This Docusaurus project was generated "
            "by DocIntel AI.",

            "",

            "## Install dependencies",

            "",

            "npm install",

            "",

            "## Start locally",

            "",

            "npm start",

            "",

            "## Build",

            "",

            "npm run build",

            "",

            "## Serve production build",

            "",

            "npm run serve"

        ]

        readme = "\n".join(
            readme_lines
        )

        (
            project_path / "README.md"
        ).write_text(

            readme,

            encoding="utf-8"

        )

        return PublishResult(

            success=True,

            message=(
                "Docusaurus project "
                "created successfully."
            ),

            location=str(
                project_path
            )

        ).to_dict()